---
- name: Build project using Cargo
  ansible.builtin.command: cargo build --release
  args:
    chdir: "{{ project_path }}"
  become: false

- name: Configure gateway systemd service
  ansible.builtin.template:
    src: "gateway.service.j2"
    dest: "/etc/systemd/system/gateway.service"
    mode: "0644"
  become: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Stop gateway if it's running
  ansible.builtin.systemd:
    name: "{{ bin_filename }}"
    state: stopped
  become: true

- name: Move the generated binary to the systemd service location
  ansible.builtin.copy:
    src: "{{ project_path }}/target/release/{{ bin_filename }}"
    dest: "/usr/local/bin/{{ bin_filename }}"
    remote_src: true
    mode: "0755"
  become: true

- name: Start gateway
  ansible.builtin.systemd:
    name: "{{ bin_filename }}"
    state: started
    enabled: true
  become: true
