version: "3.8"

services:
  stripe:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - go-mod:/go/pkg/mod
      - go-build:/root/.cache/go-build
    ports:
      - "3001:3001"
    environment:
      DB_USER: stripe
      DB_PASSWORD: password
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
      WEB_SERVER_PORT: 3001
      STRIPE_SECRET_KEY: sk_test_51OPtRcEjtf5XGOQ8CfWLHucJDdEc1mEiJ0YpdSahFC9lkvkehgX0k5vSmf8AYUcKNSlcOn7ls9X85AjvxsB2izKy00sHODun4C
      STRIPE_WEBHOOK_SECRET: whsec_f552175b933894163f38038b2a5a4527cd5397bcab8fd7524eb8b62073198079
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: stripe
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  pgdata:
  go-mod:
  go-build:
