
- name: Check if cloudflared is installed
  ansible.builtin.command: cloudflared --version
  register: cloudflared_version
  ignore_errors: true
  changed_when: false
  failed_when: false
  check_mode: no
  become: false

- name: download repo config
  ansible.builtin.get_url:
    url: https://pkg.cloudflare.com/cloudflared-ascii.repo
    dest: /etc/yum.repos.d/cloudflared-ascii.repo
  when: cloudflared_version.rc != 0
  become: true

- name: install cloudflared
  ansible.builtin.yum:
    name: cloudflared
    state: present
  when: cloudflared_version.rc != 0
  become: true
