git_repo_url: "git@github.com:FairPnP/backend.git"
git_repo_branch: master
git_repo_path: "{{ ansible_env.HOME }}/fairpnp"
api_service_project_path: "{{ git_repo_path }}/api-service"
migration_path: "{{ api_service_project_path }}/migrations"
s3_bucket_user_content: "fairpnp-dev-user-content"
aws_region: "us-east-2"
stripe_return_url: "fairpnp://stripe/return"
stripe_refresh_url: "fairpnp://stripe/refresh"
