git_repo_url: "git@github.com:FairPnP/backend.git"
git_repo_branch: master
git_repo_path: "{{ ansible_env.HOME }}/fairpnp"
project_path: "{{ git_repo_path }}/api-service"
migration_path: "{{ project_path }}/migrations"
s3_bucket_user_content: "fairpnp-dev-user-content"
aws_region: "us-east-2"
stripe_return_url: "fairpnp://stripe/return"
stripe_refresh_url: "fairpnp://stripe/refresh"

# TODO: move this to vault
google_web_api_key: "AIzaSyDMP8gXyXheqkMq8KdjZiIuM0YxADie1Z8"
