---
- name: Api-server-setup
  hosts: api-server
  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml
  gather_facts: true
  vars_files:
    - ../environments/cross_env_vars.yml
    - ../environments/{{ ENV }}/group_vars/all/env_vars.yml
    - ../environments/{{ ENV }}/group_vars/all/env_vault.yml
  roles:
    - github
    - rust
    - postgres
    - cloudflared
    - cmake
    - golang
  remote_user: ec2-user
  tasks:
    - name: Template for buildserver motd
      ansible.builtin.template:
        src: "templates/etc/motd.j2"
        dest: "/etc/motd"
        owner: root
        group: root
        mode: "0644"
      become: true
