- name: Ensure logs directory exists
  ansible.builtin.file:
    path: "{{ log_dir }}"
    state: directory
    mode: "0755"
  become: false

- name: Clone or update git repository
  ansible.builtin.git:
    repo: "{{ git_repo_url }}"
    dest: "{{ git_repo_path }}"
    version: "{{ git_repo_branch }}"
    update: true
  become: false
